### ISSUE TITLE
Needed: xw:set-selected-procedure-arguments-indices 

### ISSUE THREAD

**Issue by arthurhjorth** [qiemem/LSWidgets#6]
`xw:set-selected-procedure-arguments` currently takes a list like `[["m" "12:0-initial-number-sheep"] ["n" "12:0-initial-number-sheep"]]`. However, when we have ambiguous names, this doesn't work. So we need to find a way to directly set the selected item with an item list. I am thinking something like

`[[var-name index] [var-name2 index2], etc.]`

This (and a 3-minute cleanup of the generation of entity names) is all we need to make args work in the gui.

**Comment by qiemem** [comment]
Fixed by eeef31498ed32d0f0499354e65462b7a035bcedf
